development:
  :address: smtp.gmail.com
  :port: 587
  :domain: maktabaa.com
  :authentication: plain
  :user_name: do_not_reply@maktabaa.com
  :password: carlmorten99
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :domain: maktabaa.com
  :authentication: plain
  :user_name: do_not_reply@maktabaa.com
  :password: carlmorten99
  :enable_starttls_auto: true
